version: "3.3"
services:
    theboysbot:
        depends_on: 
            - watchtower
        build:
            context: .
            dockerfile: Dockerfile
        image: theboysbot-image
        container_name: theboysbot-container
        restart: unless-stopped
        env_file: .env
        volumes:
            - .:/home/node/theboysbot
            - node_modules:/home/node/theboysbot/node_modules
    watchtower:
        command: --label-enable --cleanup --interval 300
        image: containrrr/watchtower
        network_mode: none
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    node_modules: